# Generated by Django 5.2.8 on 2026-01-07 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manageExpedition', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.FloatField(max_length=10)),
                ('volume', models.FloatField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('id_exp', models.ForeignKey(default='JHY-52', max_length=10, on_delete=django.db.models.deletion.CASCADE, to='manageExpedition.expedition')),
            ],
        ),
    ]
