# Generated by Django 5.2.8 on 2026-01-24 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manageExpedition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.FloatField()),
                ('volume', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('id_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colis', to='manageExpedition.expedition')),
            ],
        ),
    ]
