# Generated by Django 5.2.8 on 2026-01-23 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manageExpedition', '0002_remove_expedition_id_exp_expedition_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.FloatField(max_length=10)),
                ('volume', models.FloatField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('expedition', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='manageExpedition.expedition')),
            ],
        ),
    ]
