# Generated by Django 5.2.8 on 2026-01-24 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('logistics', '0001_initial'),
        ('manageDestination', '0001_initial'),
        ('tarification', '0001_initial'),
        ('typeservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_fact', models.DateField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tournee', models.DateField()),
                ('chauffeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.chauffeur')),
                ('destinations', models.ManyToManyField(related_name='tournees', to='manageDestination.destination')),
                ('vehicule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id_Exp', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('trsit', 'en transit'), ('centri', 'en centre de tri'), ('encourslivr', 'en cours de livraison'), ('livr', 'livré'), ('echec', 'echec de livraison')], max_length=20)),
                ('date_exped', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expeditions', to='clients.client')),
                ('numBureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageDestination.destination')),
                ('tarification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarification.tarification')),
                ('type_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='typeservice.typeservice')),
                ('tournee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions', to='manageExpedition.tournee')),
            ],
        ),
    ]
