# Generated by Django 5.2.8 on 2026-01-13 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historique', '0002_remove_historique_expedition'),
        ('manageExpedition', '0002_remove_expedition_id_exp_expedition_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique',
            name='expedition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='manageExpedition.expedition'),
        ),
    ]
