# Generated by Django 5.2.8 on 2026-01-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('numBureau', models.IntegerField(primary_key=True, serialize=False)),
                ('ville', models.CharField(max_length=30)),
                ('pays', models.CharField(max_length=20)),
                ('zoneGeo', models.CharField(max_length=30)),
                ('tarifBase', models.FloatField(max_length=10)),
            ],
        ),
    ]
