# Generated by Django 6.0 on 2026-01-23 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manageDestination', '0001_initial'),
        ('typeservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifPoids', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifVolume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifications', to='manageDestination.destination')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifications', to='typeservice.typeservice')),
            ],
            options={
                'unique_together': {('destination', 'service')},
            },
        ),
    ]
