# Generated by Django 5.2.8 on 2026-01-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='expedition',
        ),
    ]
