# Generated by Django 6.0 on 2026-01-12 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '__first__'),
        ('incidents', '__first__'),
        ('manageExpedition', '0007_expedition_id_client_facture_id_client_and_more'),
        ('typeservice', '0002_remove_typeservice_delivery_delay_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_reclamation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('resolue', 'Résolue'), ('annulee', 'Annulée')], default='en_cours', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='clients.client')),
                ('expedition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='manageExpedition.expedition')),
                ('facture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='manageExpedition.facture')),
                ('incident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='incidents.incident')),
                ('typeService', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamations', to='typeservice.typeservice')),
            ],
        ),
    ]
