# Generated by Django 5.2.8 on 2026-01-24 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        ('manageExpedition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='manageExpedition.tournee'),
        ),
    ]
