# Generated by Django 5.2.8 on 2026-01-24 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_alter_incident_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='trajet',
        ),
    ]
