# Generated by Django 5.2.8 on 2026-01-07 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('incidents', '0001_initial'),
        ('manageExpedition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_reclamation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('resolue', 'Résolue'), ('annulee', 'Annulée')], default='en_cours', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='clients.client')),
                ('expedition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='manageExpedition.expedition')),
                ('facture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='manageExpedition.facture')),
                ('incident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='incidents.incident')),
            ],
        ),
    ]
