# Generated by Django 5.2.8 on 2026-01-13 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageExpedition', '0002_remove_expedition_id_exp_expedition_id_and_more'),
        ('reclamations', '0002_remove_reclamation_expedition'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='expedition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='manageExpedition.expedition'),
        ),
    ]
