# Generated by Django 6.0 on 2026-01-23 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manageExpedition', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('retard', 'Retard'), ('perte', 'Perte'), ('dommage', 'Dommage'), ('technique', 'Problème technique'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField()),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('resolu', models.BooleanField(default=False)),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='manageExpedition.tournee')),
            ],
        ),
    ]
