# Generated by Django 6.0 on 2026-01-24 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trajet', '0001_initial'),
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='trajet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Trajet.trajet', verbose_name='Trajet associé'),
        ),
    ]
