# Generated by Django 5.2.8 on 2026-01-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeservice',
            name='Delai',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='typeService',
            field=models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('international', 'International')], default='standard', max_length=30, unique=True),
        ),
    ]
