# Generated by Django 5.2.8 on 2026-01-07 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('logistics', '0001_initial'),
        ('manageDestination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_fact', models.DateField(auto_now=True)),
                ('id_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Tournée',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTourne', models.DateField()),
                ('id_chauff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.chauffeur')),
                ('id_vehicule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.vehicule')),
                ('numBureau', models.ManyToManyField(related_name='Tournee', to='manageDestination.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id_Exp', models.CharField(default='JHY-52', max_length=10, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('trsit', 'en transit'), ('centri', 'en centre de tri'), ('encourslivr', 'en cours de livraison '), ('livr', 'livré'), ('echec', 'echec de livraison')], max_length=20)),
                ('date_exped', models.DateTimeField(auto_now=True)),
                ('id_client', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('numBureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageDestination.destination')),
                ('id_tournée', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manageExpedition.tournée')),
            ],
        ),
    ]
