# Generated by Django 5.2.8 on 2026-01-13 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('manageExpedition', '0001_initial'),
        ('typeservice', '0002_typeservice_delai_alter_typeservice_typeservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedition',
            name='id_Exp',
        ),
        migrations.AddField(
            model_name='expedition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='typeservice.typeservice'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='statut',
            field=models.CharField(choices=[('trsit', 'transit'), ('centri', 'en tri'), ('encourslivr', 'en cours '), ('livr', 'livré'), ('echec', 'echec')], max_length=20),
        ),
    ]
