# Generated by Django 6.0 on 2026-01-01 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageExpedition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='id_colis',
            field=models.ManyToManyField(related_name='expedition', to='manageExpedition.colis'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='id_tarification',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='manageExpedition.tarification'),
            preserve_default=False,
        ),
    ]
