# Generated by Django 6.0 on 2026-01-03 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageDestination', '0001_initial'),
        ('manageExpedition', '0004_rename_id_facture_expedition_facture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournée',
            name='id_chauff',
        ),
        migrations.RemoveField(
            model_name='historiqueexp',
            name='id_chauff',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='id_client',
        ),
        migrations.RemoveField(
            model_name='expedition',
            name='id_client',
        ),
        migrations.RemoveField(
            model_name='expedition',
            name='id_colis',
        ),
        migrations.AlterField(
            model_name='expedition',
            name='numBureau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageDestination.destination'),
        ),
        migrations.RemoveField(
            model_name='historiqueexp',
            name='id_exp',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='reclamation',
        ),
        migrations.RemoveField(
            model_name='expedition',
            name='tarification',
        ),
        migrations.RemoveField(
            model_name='expedition',
            name='id_service',
        ),
        migrations.RemoveField(
            model_name='tournée',
            name='id_vehicule',
        ),
        migrations.RemoveField(
            model_name='expedition',
            name='facture',
        ),
        migrations.AlterField(
            model_name='tournée',
            name='numBureau',
            field=models.ManyToManyField(related_name='Tournee', to='manageDestination.destination'),
        ),
        migrations.DeleteModel(
            name='Chauffeur',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Colis',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='historiqueExp',
        ),
        migrations.DeleteModel(
            name='Reclamation',
        ),
        migrations.DeleteModel(
            name='Tarification',
        ),
        migrations.DeleteModel(
            name='typeService',
        ),
        migrations.DeleteModel(
            name='Vehicule',
        ),
    ]
