# Generated by Django 6.0 on 2026-01-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255, unique=True, verbose_name='Clé de cache')),
                ('data', models.JSONField(verbose_name='Données en cache')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
            ],
            options={
                'verbose_name': 'Cache Dashboard',
                'verbose_name_plural': 'Caches Dashboard',
                'ordering': ['-created_at'],
            },
        ),
    ]
