# Generated by Django 6.0 on 2025-12-31 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id_chauff', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.FloatField(max_length=10)),
                ('volume', models.FloatField(max_length=10)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('numBureau', models.IntegerField(primary_key=True, serialize=False)),
                ('ville', models.CharField(max_length=30)),
                ('pays', models.CharField(max_length=20)),
                ('zoneGeo', models.CharField(max_length=30)),
                ('tarifBase', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='typeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_fact', models.DateField(auto_now=True)),
                ('id_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manageExpedition.client')),
                ('id_rec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manageExpedition.reclamation')),
            ],
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('trsit', 'en transit'), ('centri', 'en centre de tri'), ('encourslivr', 'en cours de livraison '), ('livr', 'livré'), ('echec', 'echec de livraison')], max_length=20)),
                ('date_exped', models.DateTimeField(auto_now=True)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageExpedition.client')),
                ('numBureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageExpedition.destination')),
                ('id_facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageExpedition.facture')),
            ],
        ),
        migrations.CreateModel(
            name='historiqueExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePassage', models.DateField()),
                ('lieuxPassage', models.CharField(max_length=20)),
                ('id_chauff', models.ManyToManyField(related_name='histExp', to='manageExpedition.chauffeur')),
                ('id_exp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manageExpedition.expedition')),
            ],
        ),
        migrations.CreateModel(
            name='Tournée',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTourne', models.DateField()),
                ('id_chauff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageExpedition.chauffeur')),
                ('numBureau', models.ManyToManyField(related_name='Tournee', to='manageExpedition.destination')),
                ('id_vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageExpedition.vehicule')),
            ],
        ),
        migrations.AddField(
            model_name='expedition',
            name='id_tournée',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageExpedition.tournée'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='id_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageExpedition.typeservice'),
        ),
    ]
