# Generated by Django 6.0 on 2026-01-23 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('manageDestination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_fact', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tournee', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id_Exp', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('trsit', 'en transit'), ('centri', 'en centre de tri'), ('encourslivr', 'en cours de livraison'), ('livr', 'livré'), ('echec', 'echec de livraison')], max_length=20)),
                ('date_exped', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expeditions', to='clients.client')),
                ('numBureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageDestination.destination')),
            ],
        ),
    ]
