# Generated by Django 6.0 on 2026-01-23 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('logistics', '0001_initial'),
        ('manageDestination', '0001_initial'),
        ('manageExpedition', '0001_initial'),
        ('tarification', '0001_initial'),
        ('typeservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='tarification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarification.tarification'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='type_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='typeservice.typeservice'),
        ),
        migrations.AddField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='clients.client'),
        ),
        migrations.AddField(
            model_name='tournee',
            name='chauffeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.chauffeur'),
        ),
        migrations.AddField(
            model_name='tournee',
            name='destinations',
            field=models.ManyToManyField(related_name='tournees', to='manageDestination.destination'),
        ),
        migrations.AddField(
            model_name='tournee',
            name='vehicule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.vehicule'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='tournee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions', to='manageExpedition.tournee'),
        ),
    ]
