# Generated by Django 6.0 on 2026-01-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageExpedition', '0002_expedition_id_colis_expedition_id_tarification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expedition',
            old_name='id_tarification',
            new_name='tarification',
        ),
    ]
