# Generated by Django 6.0 on 2026-01-02 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageExpedition', '0003_rename_id_tarification_expedition_tarification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expedition',
            old_name='id_facture',
            new_name='facture',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='id_rec',
            new_name='reclamation',
        ),
    ]
