# Generated by Django 6.0 on 2026-01-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageExpedition', '0005_remove_tournée_id_chauff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedition',
            name='id',
        ),
        migrations.AddField(
            model_name='expedition',
            name='id_Exp',
            field=models.CharField(default='JHY-52', max_length=10, primary_key=True, serialize=False),
        ),
    ]
