# Generated by Django 6.0 on 2026-01-05 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '__first__'),
        ('logistics', '__first__'),
        ('manageExpedition', '0006_remove_expedition_id_expedition_id_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='id_client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AddField(
            model_name='facture',
            name='id_client',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournée',
            name='id_chauff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.chauffeur'),
        ),
        migrations.AddField(
            model_name='tournée',
            name='id_vehicule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.vehicule'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='id_tournée',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manageExpedition.tournée'),
        ),
    ]
