# Generated by Django 6.0 on 2026-01-12 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '__first__'),
        ('logistics', '__first__'),
        ('manageDestination', '0001_initial'),
        ('manageExpedition', '0007_expedition_id_client_facture_id_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedition',
            name='id_tournée',
        ),
        migrations.RemoveField(
            model_name='expedition',
            name='id_client',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='id_client',
        ),
        migrations.AddField(
            model_name='expedition',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AddField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='clients.client'),
        ),
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tournee', models.DateField()),
                ('chauffeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.chauffeur')),
                ('destinations', models.ManyToManyField(related_name='Tournee', to='manageDestination.destination')),
                ('vehicule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.vehicule')),
            ],
        ),
        migrations.AddField(
            model_name='expedition',
            name='tournee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions', to='manageExpedition.tournee'),
        ),
        migrations.DeleteModel(
            name='Tournée',
        ),
    ]
