# Generated by Django 6.0 on 2026-01-12 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '__first__'),
        ('historique', '0001_initial'),
        ('manageExpedition', '0008_remove_expedition_id_tournée_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historique',
            old_name='date_action',
            new_name='date_deposition',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='action',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='incident',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='reclamation',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='user',
        ),
        migrations.AddField(
            model_name='historique',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='clients.client'),
        ),
        migrations.AddField(
            model_name='historique',
            name='expedition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='manageExpedition.expedition'),
        ),
    ]
