# Generated by Django 6.0 on 2026-01-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometrage', models.FloatField(verbose_name='Kilométrage (km)')),
                ('duree', models.DurationField(verbose_name='Durée')),
                ('consommation_carb', models.FloatField(verbose_name='Consommation carburant (L)')),
            ],
            options={
                'verbose_name': 'Trajet',
                'verbose_name_plural': 'Trajets',
            },
        ),
    ]
