# Generated by Django 5.2.8 on 2026-01-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numPermis', models.CharField(max_length=50, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('disponibilite', models.BooleanField(default=True)),
                ('adresse', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numImmat', models.CharField(max_length=20, unique=True)),
                ('type_vehicule', models.CharField(max_length=50)),
                ('capacitePoids', models.FloatField()),
                ('capaciteVolume', models.FloatField()),
                ('consommationCarburant', models.FloatField()),
                ('disponibilite', models.CharField(choices=[('Dispo', 'Disponible'), ('maint', 'Maintenance'), ('onRoute', 'On Route')], default='Dispo', max_length=50)),
            ],
        ),
    ]
