# Generated by Django 5.2.8 on 2026-01-15 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_chauffeur_date_creation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chauffeur',
            old_name='Tel',
            new_name='Telephone',
        ),
    ]
