# Generated by Django 5.2.8 on 2026-01-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_rename_adress_chauffeur_adresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='etat',
        ),
        migrations.AddField(
            model_name='vehicule',
            name='disponibilite',
            field=models.BooleanField(default=True),
        ),
    ]
