# Generated by Django 6.0 on 2026-01-03 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manageExpedition', '0005_remove_tournée_id_chauff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.FloatField(max_length=10)),
                ('volume', models.FloatField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageExpedition.expedition')),
            ],
        ),
    ]
