# Generated by Django 6.0 on 2026-01-03 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageColis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colis',
            old_name='expedition',
            new_name='id_Exp',
        ),
    ]
