# Generated by Django 6.0 on 2026-01-03 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageColis', '0002_rename_expedition_colis_id_exp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colis',
            name='id_Exp',
        ),
    ]
