# Generated by Django 6.0 on 2026-01-03 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageColis', '0003_remove_colis_id_exp'),
        ('manageExpedition', '0006_remove_expedition_id_expedition_id_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='colis',
            name='id_exp',
            field=models.ForeignKey(default='JHY-52', max_length=10, on_delete=django.db.models.deletion.CASCADE, to='manageExpedition.expedition'),
        ),
    ]
