# Generated by Django 5.2.8 on 2026-01-15 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_rename_tel_chauffeur_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chauffeur',
            old_name='Adress',
            new_name='adresse',
        ),
        migrations.RenameField(
            model_name='chauffeur',
            old_name='Disponibilite',
            new_name='disponibilite',
        ),
        migrations.RenameField(
            model_name='chauffeur',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='chauffeur',
            old_name='Telephone',
            new_name='telephone',
        ),
    ]
