# Generated by Django 6.0 on 2026-01-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Standard, Express, International', max_length=50, unique=True)),
                ('delivery_delay_days', models.PositiveIntegerField(help_text='Delivery delay in days')),
            ],
        ),
    ]
