# Generated by Django 6.0 on 2026-01-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeService', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('international', 'International')], max_length=30, unique=True)),
            ],
        ),
    ]
