# Generated by Django 6.0 on 2026-01-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeservice',
            name='delivery_delay_days',
        ),
        migrations.RemoveField(
            model_name='typeservice',
            name='name',
        ),
        migrations.AddField(
            model_name='typeservice',
            name='typeService',
            field=models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('international', 'International')], default=2, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
